### ISSUE TITLE
Support for GPU based codebuild container

### ISSUE THREAD

**Issue by shankarhpatel** [awslabs/aws-codebuild-jenkins-plugin#139]
We aim to launch a GPU-based pipeline on CodeBuild, however, to do so, we require a GPU-based node. Currently, the CodeBuild Jenkins plugin only supports LINUX_CONTAINERS. We would appreciate assistance in launching a GPU-based CodeBuild project using the CodeBuild Jenkins plugin.

**Comment by leoherran-aws** [comment]
This plugin supports overriding the environment type with all [currently supported](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html) types, though some of the documentation that the plugin provides is out of date and only mentions Linux and Windows. You should also be able to trigger builds for an existing CodeBuild project that uses the GPU environment type. What specific error are you running into?

**Comment by subinataws** [comment]
@shankarhpatel - As @leoherran-aws mentioned, you should be able to use any compute type that is available in CodeBuild. Resolving.
