### ISSUE TITLE
Job configuration containing CodeBuild lost after Jenkins reboot 

### ISSUE THREAD

**Issue by krm1** [awslabs/aws-codebuild-jenkins-plugin#15]
Issue seen on Jenkins 2.32.1 with plugin code commit '0046d84' (mavenID 	com.amazonaws:aws-codebuild:1.1):

Hello, 

I'm experiencing that after a Jenkins reboot the Jenkins job containing the CodeBuild Plugin as Buildstep is losing its buildstep configuration completly. 

Thanks

**Comment by krm1** [comment]
I may add, the job configuration contains two build steps, a shell step first, followed by a CodeBuild step.

**Comment by leobaran-aws** [comment]
The configuration for the plugin is stored in <Jenkins home directory>/jobs/<project name>/config.xml under the <builders> item. Can you provide more information about the Jenkins server on which this issue occurred? It may be moving/deleting the config.xml.

**Comment by krm1** [comment]
Might be an issue with Jenkins ver. 2.32.1, I can't reproduce this error on Jenkins ver. 2.32.2. In my view the issue can be closed then.
