### ISSUE TITLE
CodeBuild Failure will be reported as success

### ISSUE THREAD

**Issue by krm1** [awslabs/aws-codebuild-jenkins-plugin#18]
A failure in phase 'PROVISIONING' will be reported by the plugin as SUCCESS although CodeBuild reported it correctly as failed.

A failure in phase 'PROVISIONING' can be caused by choosing a custom Docker image without giving it the correct Principal rights (AWS account).   https://docs.aws.amazon.com/codebuild/latest/userguide/sample-ecr.html

> Unable to pull customer's container image. AWS CodeBuild is not authorized to perform ecr:BatchGetImage on resource ... 

=>

> Build step 'Run build on AWS CodeBuild' changed build result to SUCCESS

**Comment by leobaran-aws** [comment]
The functionality you describe was introduced in [this commit](https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/71de9e942ac93e7a9a09e44b64322d5987286ed4) to make our plugin support the [Pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin). If you click on CodeBuild Dashboard in Jenkins it will show you the status of the build.

**Comment by leobaran-aws** [comment]
@takus Can you provide some insight regarding succeeding the build in Jenkins regardless of the build status in CodeBuild? I'm referring to src/main/java/CodeBuilder.java:245 in [this commit](https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/71de9e942ac93e7a9a09e44b64322d5987286ed4).

**Comment by krm1** [comment]
@leobaran-aws @takus 
I would find it best if the Jenkins plugin for CodeBuild could only report SUCCESS if all CodeBuild phases are successful. That way it makes more sense to build Jenkins job dependencies around Jenkins/CodeBuild.

**Comment by krm1** [comment]
@leobaran-aws 
Is there a workaround for this issue, I would like to have Jenkins only succeed when all of CodeBuild's phases were successful?

**Comment by krm1** [comment]
Maybe the error comes from the aws-java-sdk itself, [this code line in the plugin](https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/71de9e942ac93e7a9a09e44b64322d5987286ed4/src/main/java/CodeBuilder.java#L236) looks good to me. Is there a way to look into the code of the aws-java-sdk? Especially into the function [com.amazonaws.services.codebuild.model.Build.getBuildStatus()](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codebuild/model/Build.html#getBuildStatus--)?

**Comment by krm1** [comment]
... but I'm not a Java developer, you guys can certainly do this better ... :)

**Comment by leobaran-aws** [comment]
Assuming you're not using the CodeBuild plugin with the pipeline plugin, one possible workaround is to clone the repository, check out the commit before takus's change, and built it using maven. So you would run the following: 
`git clone https://github.com/awslabs/aws-codebuild-jenkins-plugin.git`
`git checkout c80a222`
`mvn install`
Install `target/aws-codebuild.hpi` to your Jenkins server

I'm hesitant to revert takus's change before hearing their justification, as I know very little about the pipeline plugin. I do agree that the Jenkins build should fail when the CodeBuild build fails though. Hopefully we can find a solution that works for both use cases.

**Comment by krm1** [comment]
@leobaran-aws You're right, i'm using the CodeBuild plugin in a freestyle job. [The readme has no information on how to use CodeBuild as a pipeline job](https://github.com/awslabs/aws-codebuild-jenkins-plugin/issues/22), if you could give me the pipeline snippet with the option "use Jenkins source" then I would be very happy to switch to pipeline instead of freestyle. :)

**Comment by oliver-schoenherr** [comment]
@krm1 the hidden doc for pipeline support: https://github.com/awslabs/aws-codebuild-jenkins-plugin/issues/2#issuecomment-266020096

**Comment by krm1** [comment]
@oliver-schoenherr Thanks. :)

`node {
    awsCodeBuild projectName: "mybuild",
        awsAccessKey: env.AWS_ACCESS_KEY_ID,
        awsSecretKey: env.AWS_SECRET_ACCESS_KEY,
        region: "us-west-2",
        sourceControlType: "remote"
}`

Is `sourceControlType: "remote"` "Use Project source" or "Use Jenkins source"

**Comment by leobaran-aws** [comment]
`remote` would correspond to "use project source." Use the string "jenkins" to use your source configured in Jenkins. I'll clear this up in the readme.

**Comment by krm1** [comment]
@leobaran-aws Thanks a lot :)

**Comment by leobaran-aws** [comment]
https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/63aeb32364775d470fb1c6cde8ea5e5980c401b3

I've changed the behavior in the above commit so that CodeBuild failed builds cause the Jenkins build to fail. I'll let @takus or whoever else submit another pull request if they want the other functionality--we can discuss the pros and cons there.
