### ISSUE TITLE
Plugin no longer works with codebuild using Jenkins as source

### ISSUE THREAD

**Issue by TruffleMuffin** [awslabs/aws-codebuild-jenkins-plugin#19]
A recent change to code build service by AWS has caused this plugin to stop functioning when you use Jenkins as the source.

Change was introduced on 24/02/2017 at some point. All builds (including rebuilds from existing artifacts that previously were successful) now fail on code build during DOWNLOAD_SOURCE step with

```
2017/02/25 07:40:19 Waiting for agent 
2017/02/25 07:40:37 Phase is DOWNLOAD_SOURCE 
2017/02/25 07:40:37 Source is located at /tmp/src614143422/src 
2017/02/25 07:40:37 Phase complete: DOWNLOAD_SOURCE Success: false 
2017/02/25 07:40:37 Phase context status code: YAML_FILE_ERROR Message: YAML file does not exist 
2017/02/25 07:40:37 Runtime error (YAML file does not exist) 
```

This appears to be an issue with the way the plugin creates the ZIP file. The plugin is currently adding the .git directory to the ZIP. When this is excluded code build service is able to execute correctly.

**Comment by TruffleMuffin** [comment]
This may have only effected windows jenkins versions as I also found that the zip created had a 'blank' folder at the root of the zip. There is a second commit which removes this also.

My feeling is that both are valuable as the .git directory is irrelevant to codebuild and cuts down on the site of the zip going up which is nice.

**Comment by TruffleMuffin** [comment]
A general question to go with this. The issue appeared on Friday, contacted AWS Support but they couldn't see any problems. Is there some public place where changes regarding codebuild are documented? Tracking the issue down was a bit of a pain.

**Comment by krm1** [comment]
Might be restricted to Windows Jenkins, my Linux Jenkins which ran on 26th with CodeBuild had no issues.

**Comment by TruffleMuffin** [comment]
Quite possibly, on consideration I think this is because the zip entry is constructed using File.separator, which on windows is a "\". This means unzipping on a unix system doesn't have the folder structure, just really long path file names.
