### ISSUE TITLE
Pipeline build compatability

### ISSUE THREAD

**Issue by hanks42** [awslabs/aws-codebuild-jenkins-plugin#2]
We are looking at using this plugin with Jenkins 2 using pipelines. Is that a featured that is planned to be added to this plugin?

I believe to be compatible it has to implement a SimpleBuildStep according to the [dev guide](https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md#build-steps).

**Comment by michaelneale** [comment]
yes it is pretty simple to add it if it can already do a build step. 

I wonder if there are better ways to offer a codebuild agent - ie via a label - so it provisions it as needed.

**Comment by clareliguori** [comment]
Yeah, I'll look into supporting Jenkins pipelines.  It looks someone is already trying to get this work.  I haven't tested it, but hopefully they submit a PR :)
https://github.com/takus/aws-codebuild-jenkins-plugin/commit/13cbec5297f5f05bd0f4203eac24d923d6050edb

**Comment by takus** [comment]
Hi, I'm trying to support Jenkins pipelines as you mentioned. My changes work well on my Jenkins for now. But I'm not sure how to contribute this project. Just submitting a PR is okay for you?

**Comment by clareliguori** [comment]
Yep, contributions via PR are welcome!

**Comment by clareliguori** [comment]
@michaelneale Can you explain what you mean by offering a CodeBuild agent / using labels?  I'm not personally super familiar with Jenkins, but I'm gathering you mean provisioning a slave?  All the resources for a build in CodeBuild are provisioned on-demand for each build, but they don't act as a Jenkins slave per-se (the plugin polls the status of the CodeBuild build it started).

**Comment by michaelneale** [comment]
@clareliguori yes exactly. I am trying to find an example of this. The closest I can think of isn't a super clear example, but https://github.com/jenkinsci/docker-slaves-plugin does a similar thing in pipeline: 

```
dockerNode(image: "maven:3.3.3-jdk-8", sideContainers: ["selenium/standalone-firefox"]) {
  git "https://github.com/wakaleo/game-of-life"
  sh 'mvn clean test'
}
```

This uses the docker api to provision on demand, but in a pipeline. I am not sure how applicable this result is. 

Perhaps the change @takus has (is there a PR?) may make a better starting point (I assume it is a step for pipeline?) - in any case - yes on demand is the intention.

**Comment by takus** [comment]
@michaelneale 
Current pipeline syntax of my changes is like this. Is this what you expected?

```
node {
    awsCodeBuild projectName: "mybuild",
        awsAccessKey: env.AWS_ACCESS_KEY_ID,
        awsSecretKey: env.AWS_SECRET_ACCESS_KEY,
        region: "us-west-2",
        sourceControlType: "remote"
}
```

**Comment by michaelneale** [comment]
@takus so what defines what command to run? or is this using an already setup codebuild project?

**Comment by takus** [comment]
@michaelneale 
Current syntax supports only what you can configure in Web UI. Thus, you need to setup CodeBuild project before defining in Jenkinsfile.

**Comment by jonathanhle** [comment]
+1

**Comment by Japster24** [comment]
+1

**Comment by taoyong-ty** [comment]
We have merged takus' commit into master.

https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/3
