### ISSUE TITLE
awsCodeBuild: This step has not yet defined any visual configuration.

### ISSUE THREAD

**Issue by krm1** [awslabs/aws-codebuild-jenkins-plugin#22]
I have learned in [this github issue ](https://github.com/awslabs/aws-codebuild-jenkins-plugin/issues/18#issuecomment-280487634) that the awsCodeBuild plugin also supports Jenkins pipeline.

But the Snippet Generator (Jenkins 2.3.2) doesn't lets you generate a groovy snippet for awsCodeBuild, it only displays the message 'This step has not yet defined any visual configuration.'

Could you therefore please:

a) Add visual configuration 
b) Add a sample snippet for pipeline to the Readme.md?

**Comment by leobaran-aws** [comment]
https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/8840317859700952aede28e61b70c7ce0e98ed4d

**Comment by krm1** [comment]
@leobaran-aws Thanks. :)
