### ISSUE TITLE
Running the plugin in parallel fails

### ISSUE THREAD

**Issue by krm1** [awslabs/aws-codebuild-jenkins-plugin#23]
When running the Jenkins CodeBuild plugin (24337ae) on Jenkins (version 2.32.3) in parallel the plugin will fail with:

```
[AWS CodeBuild Plugin] Uploading source to S3.
[AWS CodeBuild Plugin] channel is already closed
```

To reproduce you need to have a CodeBuild project and need two Jenkins jobs running in parallel which checkout from git (different branches) and use the plugin with "jenkins" as source.

**Comment by leobaran-aws** [comment]
I'm having trouble reproducing this. Are you using a Jenkins Pipeline to run these jobs in parallel?

**Comment by leobaran-aws** [comment]
I see the problem now. As a workaround, I would suggest setting the number of executors per node to one or unchecking the "Execute concurrent builds if necessary" box in your project configuration. We're working on a fix for this.

**Comment by leobaran-aws** [comment]
https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/63aeb32364775d470fb1c6cde8ea5e5980c401b3

Thank you for bringing this to our attention!
