### ISSUE TITLE
Update aws sdk version to allow for new regions

### ISSUE THREAD

**Issue by rhyslewissnapper** [awslabs/aws-codebuild-jenkins-plugin#24]
The aws-java-sdk-bom version is currently 1.11.63, which means that the com/amazonaws/partitions/endpoints.json file from aws-java-sdk-core only has 4 regions, but there are a whole lot more available now.  Could you update to 1.11.114 or greater so that the other regions are included too.  (pom.xml:157)

**Comment by dennisoehme** [comment]
+1

Please update this plugin to support more regions.

**Comment by subinataws** [comment]
Update to 1.11.123. Thanks for catching this.
