### ISSUE TITLE
Jenkins Source uploaded to S3 is not encrypted

### ISSUE THREAD

**Issue by ThatCoalGuy** [awslabs/aws-codebuild-jenkins-plugin#25]
Using the Jenkins Source being uploaded to S3, the source is uploaded without encryption. Is there plans to add encryption (either Server Side Encryption or Customer Side Encryption?)

**Comment by leobaran-aws** [comment]
I'll add this to the feature requests for the plugin. Thanks!

**Comment by leobaran-aws** [comment]
670388c1eb8d056dc8ae6aac0674277d2451e312
We've added an option to encrypt source that the plugin uploads to S3. This will be available in version 0.14, which can be downloaded [here](https://updates.jenkins.io/download/plugins/aws-codebuild/) in a few hours. Thanks for the feature request and let us know if this works for your use case.
