### ISSUE TITLE
 Unable to extract S3 bucket from object ARN.

### ISSUE THREAD

**Issue by jameszh** [awslabs/aws-codebuild-jenkins-plugin#26]
Jenkins and the plugin are all latest release.

Following the steps for:  "Using AWS CodeBulid with source only available inside of your VPC"
Manual build from AWS console, it works successful, source code checkout from git is ok, but when starting build phase with the plugin, IAM permission is correct, but I got following error. 

`java.lang.RuntimeException: Unable to extract S3 bucket from object ARN.
at Utils.getS3BucketFromObjectArn(Utils.java:24)
at CodeBuilder.perform(CodeBuilder.java:132)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at hudson.model.Build$BuildExecution.build(Build.java:206)
at hudson.model.Build$BuildExecution.doRun(Build.java:163)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
at hudson.model.Run.execute(Run.java:1728)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:405)
Build step 'Run build on AWS CodeBuild' marked build as failure
Finished: FAILURE`

**Comment by johnhanks1** [comment]
His James,

Just double checking does the arn of the bucket that you're trying to upload your source look like,

arn:aws:s3:::my_corporate_bucket

http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-s3

**Comment by jameszh** [comment]
Hi John,  does  it pull s3 info from the codebuild project,  I checked with awscli, it only returns bucket/key format, not in arn.

**Comment by johnhanks1** [comment]
Hi James to debug this future I'm going to need to know you AccountID, and ProjectName.

If you're ok sharing those here that would be great, otherwise could you please open up a thread of the AWS Forums under CodeBuild. This would allow us to private message this information. Github doesn't have private messaging.

**Comment by jameszh** [comment]
I had experienced that things behave differently from region to region, I’m running both in us-east-1 and us-east-2, have you tried these regions?

**Comment by jameszh** [comment]
I opened a case, add project name in the case note: case-id: 2184680581

Thanks,
James

**Comment by johnhanks1** [comment]
Hi James,

I have looked into your project. Did you create your project through the CLI? Looks like you have exposed a bug in our Jenkins plugin. We are working on a fix now.

**Comment by jameszh** [comment]
yes, I created with cli.

**Comment by leobaran-aws** [comment]
Thanks for bringing this to our attention, we're working on a fix right now.

**Comment by leobaran-aws** [comment]
https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/0c0c5a1fd63bdff5fc8697fa0fd067001630afcc

**Comment by leobaran-aws** [comment]
You can download the plugin with this change here: https://wiki.jenkins-ci.org/display/JENKINS/AWS+CodeBuild+Plugin

**Comment by jameszh** [comment]
thanks, this works!.
