### ISSUE TITLE
Step green even if build fails

### ISSUE THREAD

**Issue by uttamk** [awslabs/aws-codebuild-jenkins-plugin#28]
I am using the aws-codebuild plugin from a pipeline script using
`awsCodeBuild projectName: project_name, awsAccessKey: "key", awsSecretKey: "secret", region: "region", sourceVersion: "commit_sha"`
When the code build build fails, the main build shows red. When you go to `pipeline steps` 
#### Expected behaviour
The step should show up as red

#### Actual behaviour
The step shows up as blue/green

<img width="1036" alt="screenshot 2017-06-13 19 22 48" src="https://user-images.githubusercontent.com/109035/27085921-425e2466-506e-11e7-9365-ac1603f7a710.png">
Ours is quite a complicated project with a lot of parallel steps. It makes it hard to figure out what actually failed (since the console is not that helpful with parallel steps making it confusing)

**Comment by leobaran-aws** [comment]
Thanks for bringing this to our attention--we are working on a fix.

**Comment by uttamk** [comment]
Thanks @leobaran-aws. I was working on a fix before I saw your reply. I have a PR for it.
https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/29.

**Comment by uttamk** [comment]
https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/29 fixes this issue.
