### ISSUE TITLE
Get S3 uploaded artifact to Jenkins server

### ISSUE THREAD

**Issue by dwdraju** [awslabs/aws-codebuild-jenkins-plugin#33]
Is this feature or any way for so is available? I couldn't find it. Thanks.

**Comment by leobaran-aws** [comment]
We are planning on implementing this feature soon. As a workaround, you could add a post build step in Jenkins which downloads the artifact from S3.

**Comment by uttamk** [comment]
@leobaran-aws how can I know which S3 url to download from ? (assuming that there a different artifact for every run)

**Comment by leobaran-aws** [comment]
The best approach may be to keep your artifact name static and upload it to a versioned bucket. Then you could use the AWS CLI to download it from S3.

**Comment by uttamk** [comment]
@leobaran-aws I have an alternative approach for artifacts. https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/38. Let me know what you think

**Comment by dwdraju** [comment]
@uttamk I solved this using trigger. When build succeeds, it triggers another pipeline job which gets the artifact zip from S3 to jenkins server and deploy from there.

**Comment by uttamk** [comment]
That is a good workaround @dwdraju if you have only one job running at a time. In our case we can have multiple jobs running parallely (one per branch). In this case one artifact can be overwritten by another job quite easily before collecting and archiving it. Hence we need to uniquely identify artifacts

**Comment by leobaran-aws** [comment]
https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/38 solves this issue. Thanks for the feedback.
