### ISSUE TITLE
Plugin does not allow users to pass in environmentVariablesOverride properties

### ISSUE THREAD

**Issue by kaitea** [awslabs/aws-codebuild-jenkins-plugin#39]
Plugin does not allow users to pass in environmentVariablesOverride properties

the plugin is very limiting since it does not allow users to pass in environmentVariablesOverride properties

e.g. hence, we cannot pass in properties like artifactVersion to have codebuild build docker image and tag it appropriately with the supplied version

is it possible to add this feature? it would be really useful

thanks!

**Comment by leobaran-aws** [comment]
Thanks for your feedback--this is a feature that we're actively working on adding. I'll update you when it's released.

**Comment by kaitea** [comment]
thank you so much, we are eagerly awaiting this update.  :)

**Comment by leobaran-aws** [comment]
c8dcdd66454c003ea6f69a091c351890ec0e8ba2

We'll release a new version (0.12) of the plugin today. It should be available [here](http://updates.jenkins-ci.org/download/plugins/aws-codebuild/) in a few hours. Thanks for the feedback!

**Comment by kaitea** [comment]
works great, thanks so much, we just noticed one issue with the snippet generator, it generate the command with single quote so it doesn't pick up the actual value that we pass in, but changing it to double quotes fixed it

**Comment by kaitea** [comment]
also, just to confirm, the new plugin version sets the environmentVariablesOverride ? and does not touch the actual environment values in the project config itself, correct?

**Comment by leobaran-aws** [comment]
Great, thanks for the feedback! Yes, it sets environmentVariablesOverride for startBuild, which does not modify any project-level environment variables.
