### ISSUE TITLE
Using IAM role for Jenkins 

### ISSUE THREAD

**Issue by rvlasyuk** [awslabs/aws-codebuild-jenkins-plugin#4]
I've tried to use Jenkins IAM role( which worked when checked from aws-cli ) instead of AWS Access Key and AWS Secret Key and left these fields empty, but got an error:
`[AWS CodeBuild Plugin] CodeBuild configured improperly in project settings 
Enter valid AWS access and secret keys (Service: null; Status Code: 0; Error Code: null; Request ID: null)`

should it work?

**Comment by xinw0911** [comment]
Hi,
AWS Access Key and AWS Secret Key are always required when submit a build via Jenkins. They shouldn't be left empty.

**Comment by taoyong-ty** [comment]
pull request has merged. resolving.. https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/14
