### ISSUE TITLE
Allow specifying a role instead of aws credentials for IAM Access

### ISSUE THREAD

**Issue by josegonzalez** [awslabs/aws-codebuild-jenkins-plugin#41]
Rather than have keys running around in repositories that run Jenkins pipelines, it would be great if we could delegate role access to the codebuild plugin for specific jobs. Not sure how that would work underneath, but would be a nicer way of hiding credentials from users.

**Comment by leobaran-aws** [comment]
Thanks, we're actually working on this feature right now.

**Comment by leobaran-aws** [comment]
44f4a9d9c978dfe63c992f199c247f84e09e8e73
This will be available in version 0.14, which can be downloaded [here](https://updates.jenkins.io/download/plugins/aws-codebuild/) in a few hours. You'll have to create new credentials in Jenkins (of type CodeBuild Credentials) and use the id in your pipeline script (example below). You can configure these credentials to use an IAM role for authorization, but you'll still need access and secret to set that up. Let us know if this works for your use case. 

```awsCodeBuild credentialsType: 'jenkins', credentialsId: 'id123', projectName: 'project', region: 'us-east-1', sourceControlType: 'jenkins'```
