### ISSUE TITLE
Paramiterized build does not work

### ISSUE THREAD

**Issue by justinfalk** [awslabs/aws-codebuild-jenkins-plugin#43]
Hi,

I'm trying to create a build task that accepts a commit id as a parameter.  

![screen shot 2017-08-04 at 11 38 50 am](https://user-images.githubusercontent.com/16879499/28977980-cfa7ca98-7909-11e7-915a-99011d6a4ad7.png)

and then use this value as the project source control version.

![screen shot 2017-08-04 at 11 39 08 am](https://user-images.githubusercontent.com/16879499/28978008-e6c552ae-7909-11e7-8152-14d7e9f50252.png)

However, the variable does not appear to be getting substituted as shown in the log below

`[AWS CodeBuild Plugin] Starting build with project name xxxxx and source version $COMMIT_ID`

It would be great if parameters were supported.  Thanks in advance for any assistance.

**Comment by leobaran-aws** [comment]
Thanks for bringing this to our attention, I'll add support for parametrized builds as soon as possible. You should be able to get this behavior in a Jenkins pipeline script, so you could use that as a temporary workaround.

**Comment by leobaran-aws** [comment]
a69e36db7ba192024e0d05b46fe69f3669ebf717
This will be available in version 0.14, which can be downloaded [here](https://updates.jenkins.io/download/plugins/aws-codebuild/) in a few hours. Thanks again for the feedback!

**Comment by justinfalk** [comment]
Thanks!
