### ISSUE TITLE
CodeBuild failure does not fail the Jenkins build

### ISSUE THREAD

**Issue by TruffleMuffin** [awslabs/aws-codebuild-jenkins-plugin#44]
Hey,

I have had an issue in a number of builds where when codebuild fails, the build in Jenkins does not fail.

The current build status in the codebuild dashboard is "Failed", but the Jenkins build is 'Green'.

I think that a codebuild failure should fail the Jenkins build.

**Comment by leobaran-aws** [comment]
We should be throwing an exception upon build failure, but it looks like that behavior was abstracted into a file specific to pipeline builds in [this](https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/9b78d015eaa19a132b26ab2f2d89a7dc915b1d95#diff-00625793f572ec7ae6448e5857add9f1) commit. I'll make sure non-pipeline builds get this functionality as well.

**Comment by TruffleMuffin** [comment]
Thanks very much

**Comment by leobaran-aws** [comment]
14946eb78e2738d9811db88c159e69bf896a14e2
This will be available in version 0.14, which can be downloaded [here](https://updates.jenkins.io/download/plugins/aws-codebuild/) in a few hours. Thanks again for bringing this to our attention.
