### ISSUE TITLE
The plugin cannot use folder specific credentials

### ISSUE THREAD

**Issue by cartolari** [awslabs/aws-codebuild-jenkins-plugin#48]
If I create a CodeBuild credential inside a folder, I cannot use it inside CodeBuild. The credential does not appear inside the pipeline syntax generator neither is found when I run the job.

**Comment by leobaran-aws** [comment]
I'm not sure how to reproduce this. How do I create a set of CodeBuildCredentials in a folder? Does this require another plugin?

**Comment by cartolari** [comment]
The folder is created by the [CloudBees folder plugin](https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin), which I think it's a dependency of the Pipeline plugin.
I think if you create a new Jenkins installation with the default set of plugins the folder plugin will already be installed.

After installing the plugin click in New Item, there should be an option to create a folder, create it and click on it in the main dashboard view. Inside the folder (and really must be inside the folder) click the Credentials link in the left pane.The folders plugin will allow you create credentials scoped only to projects inside this folder, so projects in other folders cannot see the credentials.

Also if you click on the Pipeline Syntax link (again, inside the folder) and try to generate a snippet for this plugin it will offer help to create a credential, before creating it'll offer an option to select the scope of the credential. Even if I create a Folder scoped credential I cannot use it, also I've opened the issue here because simple text folder scoped credentials work for me, so it led me to believe the problem might be this plugin.

I hope to have provided enough information. If you need more details to help find the issue, please, let me know.

**Comment by leobaran-aws** [comment]
Thanks for letting us know, we're working to fix this issue. In the meantime you could store your secrets as global credentials and use those in your folder project.

**Comment by cartolari** [comment]
It's the workaround I'm using

**Comment by leobaran-aws** [comment]
I added support for folder credentials in e293fd1df9081222ca98777f408b89ad0e01aab0.
