### ISSUE TITLE
Environment variables by overrides are broken

### ISSUE THREAD

**Issue by the40san** [awslabs/aws-codebuild-jenkins-plugin#50]
If any whitespace contains in the Environment variables, it will be removed all whitespaces. 
(ex: "git status" should become "gitstatus" in codebuild)

It looks like force replaced by plugin.
https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/227ce8783b37183513767eb22be06c62b3070c44/src/main/java/CodeBuilder.java#L470

Could we fix that?

**Comment by leobaran-aws** [comment]
Thank you for letting us know, we are fixing this right now.

**Comment by leobaran-aws** [comment]
Fixed by e46dd908869616b3387d16a63e8e01163f15dcef. 

We'll release a new version of the plugin by the end of the day.

**Comment by the40san** [comment]
@leobaran-aws Thank you !
