### ISSUE TITLE
Print out CodeBuild link in the console output

### ISSUE THREAD

**Issue by kaitea** [awslabs/aws-codebuild-jenkins-plugin#51]
It would be great if the CodeBuild plugin prints out the actual CodeBuild job link when it starts running in the Jenkins console output.

Thanks!

**Comment by leobaran-aws** [comment]
Thanks for the feedback, we'll add this to the console output.

**Comment by leobaran-aws** [comment]
Fixed in 95b0e323130955eabae4d84f0e52759c58fa3cee. Thanks for your patience!
