### ISSUE TITLE
IAM Role Help file not found

### ISSUE THREAD

**Issue by Sandmania** [awslabs/aws-codebuild-jenkins-plugin#57]
[credentials.jelly](https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/a69e36db7ba192024e0d05b46fe69f3669ebf717/src/main/resources/CodeBuildCredentials/credentials.jelly#L58) points to a non existent help file (help-IAMRole.html). This results in an error on the Add Credentials page, when IAM Role ARN help is being accessed: 

> ERROR: Failed to load help file: Not Found

I'm guessing the correct file would be help-iamRoleAuth.html

**Comment by leobaran-aws** [comment]
Thanks for notifying us of this, we'll fix it shortly.

**Comment by leobaran-aws** [comment]
Fixed in b83387c36b09c9e8ddce3921bfceff75cd890f88. Thanks again.
