### ISSUE TITLE
Plugin not working on a windows based jenkins installation

### ISSUE THREAD

**Issue by TruffleMuffin** [awslabs/aws-codebuild-jenkins-plugin#6]
There appears to be a bug with S3DataManager.java. 

```String zipFilePath = sourceFilePath.substring(0, sourceFilePath.lastIndexOf("/")) + "/" + localfileName;```

Assumes that the path uses directory structure based around "/". On windows, this is not the case. For example, ```C:\Program Files (x86)\Jenkins\workspace\my-project```.

This results in the console error message ```[AWS CodeBuild Plugin] String index out of range: -1``` during the build process.

Suggested fix is changing to ```String zipFilePath = sourceFilePath + "/" + localfileName;```. However, I am not really familiar with Java and there may be much better solutions to this so have not submitted a pull request.

**Comment by TruffleMuffin** [comment]
Perhaps ```String zipFilePath = sourceFilePath.substring(0, sourceFilePath.lastIndexOf(File.separator)) + File.separator + localfileName;``` might be better?

**Comment by TruffleMuffin** [comment]
Will issue a pull request for this shortly.

**Comment by taoyong-ty** [comment]
Hi Gareth,

I ran a mvn:test in a windows machine and a couple of unit tests still failed even with you fix. There are other places relied on the "/" file separator assumption in our code.

I will take a closer look and submit a fix this week.

**Comment by TruffleMuffin** [comment]
Hey

I had a little trouble with the tests on windows because of issue #5. I did the development/test work on a Mac. However, with this fix in place I haven't had any further problems in a windows hosting environment.

Thanks for taking a closer look.

**Comment by taoyong-ty** [comment]
Yes I was seeing the same tests failing on my windows. "zipSource usage: prefixToTrim must be contained in the given directory"

I just pushed a commit https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/3864b2c66630fc7a84196d2d5e3158ed43e224e7 to master. This issue and issue #5 should be fixed now.
