### ISSUE TITLE
non-S3 input sources not supported

### ISSUE THREAD

**Issue by katieschilling** [awslabs/aws-codebuild-jenkins-plugin#62]
Hi Team,

The readme implies that one can use GitHub (or BitBucket, etc) as the input source instead of S3. However, in the [validation of the projectName](https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/9541d89e6ad44bb049c013cd44166eae30192fb1/src/main/java/CodeBuilder.java#L211), if the source for the existing project is anything but S3, the project is invalid and fails.

The plugin should support non-S3 inputs as is consistent with the documentation.

**Comment by leobaran-aws** [comment]
S3 source is required for the CodeBuild project if you are using your Jenkins source with CodeBuild (source control type [`jenkins`](https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/master/src/main/java/enums/SourceControlType.java#L19)). In this case, it will zip up whatever source Jenkins has checked out and upload it to S3, which CodeBuild then downloads for the build. 

Projects with other source types work as well, you just need to make sure the source control type is set to [`project`](https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/master/src/main/java/enums/SourceControlType.java#L18). The plugin will then start a build using whatever source is configured in the CodeBuild project.
