### ISSUE TITLE
Line truncation at 197 chars, possible to change this?

### ISSUE THREAD

**Issue by davidporter-id-au** [awslabs/aws-codebuild-jenkins-plugin#68]
Hi there, nice project btw. 

I'm using this from Jenkins for most of our infra builds. However, I was wondering if I may either remove/update/make-configurable the [truncation of logs](https://github.com/awslabs/aws-codebuild-jenkins-plugin/blob/master/src/main/java/CloudWatchMonitor.java#L38) coming back from cloudwatch? 

Since we do CI/cd for everything, there's frequently fairly long lines (such as CFN updates and the like) and these being truncated is confusing for the average developer who is uninterested in the minutiae of CD pipelines. 

Is there any problem or reasoning to not simply raise this this a fair bit (say 2000?). It'd just make the UX a fair bit nicer.

**Comment by Kaixiang-AWS** [comment]
Thank you for this feature request, I have passed it to the team for further review. Your feedback is very much appreciated.

**Comment by leobaran-aws** [comment]
Fixed with cfa1282ca92a4d19192523f2ab3d9253c66d13a1. Thanks for the feedback!
