### ISSUE TITLE
About Codebuild Projects

### ISSUE THREAD

**Issue by Vidyapreetha** [awslabs/aws-codebuild-jenkins-plugin#69]
Is it necessary to create a new Codebuild project for each repository that has the same buildspec.yml file. Like, I have a project on COdebuild, but I have many repositories. Do I need to make a Codebuild project for each repository?

**Comment by leobaran-aws** [comment]
No, that is not necessary. You can create one project and override the source location programmatically for each build you run. We will also support multiple source locations in the future, so the build will be able to clone multiple repositories in a single build.
