### ISSUE TITLE
Building previous commits when using $GIT_COMMIT on Source Control Version

### ISSUE THREAD

**Issue by andrefcpimentel** [awslabs/aws-codebuild-jenkins-plugin#71]
I'm having and issue when setting the Build step to 'Use Project Source' and setting the Source Control Version to $GIT COMMIT.
Jenkins fetches the right commit but on the build step it builds the previous commit on the branch.
I'm using 'Use Jenkins Source' now, but I need to go back using 'Use Project Source'.

Thanks,

Andre

**Comment by leobaran-aws** [comment]
That's certainly unexpected behavior. Have you confirmed that your CodeBuild project's source is the same as your Jenkins source? When using Jenkins source, the plugin uploads whatever is checked out in Jenkins to S3 and tells your CodeBuild project to build that specific S3 object version. For the project source option, the plugin just triggers a build with your project's configured source (and an optional source version). 

And you are using `$GIT_COMMIT` as your optional source version, correct? The variable you mentioned is missing an underscore.
