### ISSUE TITLE
add ability to use subset of jenkins source

### ISSUE THREAD

**Issue by gferreri** [awslabs/aws-codebuild-jenkins-plugin#75]
When invoking codebuild with `sourceControltype: 'jenkins'` the entire Jenkins workspace is uploaded to S3 for the codebuild job to pick up. In some cases, it would be helpful to limit the contents shared to codebuild to a single folder within the Jenkins workspace.

This is useful in situations where the source Jenkins workspace is a large monorepo, or the Jenkins pipeline contains parallel steps where a different parallel step is modifying files in the workspace. The latter scenario actually leads to a failure in the codebuild step.

**Comment by leobaran-aws** [comment]
Great idea, thanks for the feedback. I'll update you when we start implementing this.

**Comment by leobaran-aws** [comment]
Version 0.34 has a bug in which the `workspaceSubdir` attribute is not properly propagated. 29f2fa137e5b8c415e07c4d638dd56b7c9ccca54 fixes this, so please update to version 0.36.
