### ISSUE TITLE
Configure "Image pull credentials"

### ISSUE THREAD

**Issue by caiohaz** [awslabs/aws-codebuild-jenkins-plugin#78]
It's possible change default image pull credential from "AWS CodeBuild credentials" to "Project Service Role"? I need this to use a docker image from private ECR repo in "imageOverride". 

 ![pull](https://user-images.githubusercontent.com/10849509/52852653-5d80e480-3100-11e9-8277-59ecae58c141.png) 

Or i need create a new codebuild project?

**Comment by leobaran-aws** [comment]
The plugin does not yet support overriding `imagePullCredentialsType`, but you can edit your existing CodeBuild project via the console or AWS CLI to use `SERVICE_ROLE` for that attribute.

**Comment by caiohaz** [comment]
Ok, i got it, thanky you!

**Comment by leobaran-aws** [comment]
Not a problem, let us know if you have any more questions.
