### ISSUE TITLE
CodeBuildException on zip

### ISSUE THREAD

**Issue by caiohaz** [awslabs/aws-codebuild-jenkins-plugin#80]
Hello, 

When the Codebuild plugin will zip the source code and i have the file "vendor/bin/zf.php" i have the error:

> CodeBuildException
> 	at CodeBuildStep$CodeBuildExecution.run(CodeBuildStep.java:608)
> 	at CodeBuildStep$CodeBuildExecution.run(CodeBuildStep.java:566)
> 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
> 	at hudson.security.ACL.impersonate(ACL.java:290)
> 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Finished: FAILURE

If i remove this folder the plugin works.

Regards

**Comment by leobaran-aws** [comment]
Are there any additional error messages? If you are running a pipeline build, you can catch the exception and print the error message with 
```
try {
  awsCodeBuild ...
} catch (CodeBuildException e) {
  echo e.getCodeBuildResult().getErrorMessage()
}
```

**Comment by caiohaz** [comment]
@leobaran-aws It's works with declarative pipeline?

**Comment by leobaran-aws** [comment]
I believe so. Can you post the entire console log?

**Comment by caiohaz** [comment]
I just have this error. I will add a zip+awscli step before awscodebuild because i need build 2 images (in parallel), if i use the plugin the source code is copied twice to s3, right?

**Comment by leobaran-aws** [comment]
You can actually add a command to zip your source and then specify a path to the zip file (with `localSourcePath`) that the plugin will upload to S3. I'm not sure what you mean about copying the source to S3 twice. 

What the plugin does is upload your zip to a versioned S3 bucket and start a build with that S3 object version. So if you run two `awsCodeBuild` steps, each will upload the zip.

**Comment by caiohaz** [comment]
Right, and there are some problem if i run two awsCodeBuild steps in parallel?

**Comment by leobaran-aws** [comment]
No, you can run an arbitrary number of `awsCodeBuild` steps in parallel.

**Comment by caiohaz** [comment]
Ok, i will try, thank you so much!

**Comment by leobaran-aws** [comment]
Cool, let me know if you have any other questions!
