### ISSUE TITLE
Always building master branch

### ISSUE THREAD

**Issue by robosung** [awslabs/aws-codebuild-jenkins-plugin#84]
Not sure what I'm doing wrong but it appears that my jobs are always running build against the master branch on code build, regardless of which branch initiated the build on jenkins.  The behavior is the same on both pipeline and freestyle build jobs.

For the pipeline job, I'm using multibranch pipeline job and below is my job spec

```
node {
    stage("Call codebuild") {
        awsCodeBuild projectName: "rsung-test",
                     region: "us-east-1",
                     sourceControlType: "project",
                     credentialsId: "JenkinsCodeBuild",
                     credentialsType: "jenkins"
    }

}
```
Attached is a screenshot of the jenkins console log. 

![rsung-test_»_release_1_0__9_Console__Jenkins_](https://user-images.githubusercontent.com/471863/59552172-59db5e00-8f38-11e9-8348-ed83da526796.png)

The build is triggered by commit **560ca7b015b489d8d0ade03c4e9301dff0746de6** (from release/1.0 branch) but codebuild job is reading **1c8f85c9610f464b4b85571f3911fc83f0082f5b** (latest commit in master) as CODEBUILD_RESOLVED_SOURCE_VERSION.

Please advise

**Comment by leobaran-aws** [comment]
Using `sourceControlType` of type `project` will start a build using whatever source is configured in your CodeBuild project, which will in turn check out the HEAD commit on the master branch. You'll need to set the `sourceVersion` field, passing in whatever commit or branch you want to check out in your build.

**Comment by robosung** [comment]
Thanks @leobaran-aws.  I'm trying to set `sourceVersion` but it seems like COMMIT_ID isn't supported in multibranch pipeline jobs.    In what I'm trying to do, is there a better/recommended approach?

Thanks.

**Comment by robosung** [comment]
Figured it out:

```
    stage("Call codebuild") {
        checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: "<my_git_repo>"]], branches: [[name: env.BRANCH_NAME]]], poll: false
        commitId = sh(returnStdout: true, script: 'git rev-parse HEAD')
        awsCodeBuild projectName: "rsung-test",
                     region: "us-east-1",
                     sourceControlType: "project",
                     credentialsId: "JenkinsCodeBuild",
                     credentialsType: "jenkins",
                     sourceVersion: commitId
    }
```

**Comment by leobaran-aws** [comment]
Good to hear! Thanks for the update.
