### ISSUE TITLE
Add us-gov-west-1 region

### ISSUE THREAD

**Issue by sfernandezf** [awslabs/aws-codebuild-jenkins-plugin#86]
AWS recently added CodeBuild Service on Gov Cloud, specifically us-gov-west-1 region. Having this plugin compatible with Gov Cloud would be excellent for the folks that use Gov Cloud. Thank you

**Comment by leobaran-aws** [comment]
We'll push out a new version of the plugin to support this by the end of the day.

**Comment by leobaran-aws** [comment]
Fixed in a0a6e75e5ae489405adcd79cd9eef1a3fcfbb298. We'll release this in version `0.42`.

**Comment by sfernandezf** [comment]
Thanks, tested and it is perfect.
