### ISSUE TITLE
Local file locks cause full job failure

### ISSUE THREAD

**Issue by direwolf79** [awslabs/aws-codebuild-jenkins-plugin#87]
We have Jenkins configured on Windows server, which can lead to some known issues related to file deletion, largely related to Antivirus and other random file locks.  This has created a situation where multiple codebuild projects are set to a failed state in our environment when using the Upload to S3 options.

For Example...

[AWS CodeBuild Plugin] Using credentials provided by the DefaultAWSCredentialsProviderChain for authorization
[AWS CodeBuild Plugin] Zipping directory to upload to S3: D:\Deployments\<ProjectDir>
[AWS CodeBuild Plugin] Uploading to S3 at location <S3 Bucket>/<Project>.zip. MD5 checksum is <MD5SUM>
[AWS CodeBuild Plugin] Unable to delete 'D:\Deployments\9652ffb7-410b-48cf-a727-2fcc221491b0-<ProjectName>.zip'. Tried 10 times (of a maximum of 10) waiting 5 sec between attempts.
Build step 'AWS CodeBuild' changed build result to FAILURE

Would it be possible to simply notify at this stage and not stop the entire job?.... When checking S3 the newest source is always uploaded, However the plugin tries to clean up after itself (which I very much see as a good thing).  However, to complete the task in its current state All that is really necessary is to kick off the code build project directly through the Code Build console, as the file is properly uploaded to S3 and ready for use in Codebuild, and at least for my setup a notice that there are files that need to be cleaned up is more than enough (we are not currently using a full CI pipeline and our Dev's still prefer to 'click' the build button in Jenkins at this time).

Alternately if the zip could be created in the project directory rather than the root of the configured jenkins jobs directory I could just enable "delete workspace before build" in the jenkis job itself.

**Comment by leoherran-aws** [comment]
Thanks for your feedback! I'll look into whether we can implement both of your recommendations (emit a warning when deletion fails and store the zip file in the project's workspace).

**Comment by direwolf79** [comment]
If possible that would be simply wonderful.  I fully understand that I we are likely in the minority by running Jenkins on Windows (tho I am sure I am not alone), and the randomness of file locks really creates quite a few headaches, and this would remove one of the largest we regularly run into.  If there is anything I can do to assist or help test let me know.

**Comment by leoherran-aws** [comment]
I added some logic to swallow exceptions when deleting the source zip file (released in version `0.46`). Let me know if it helps with your use case.

**Comment by direwolf79** [comment]
Just updated this morning, will do some testing and get back to you.  Thank you for taking the time to look into it.

**Comment by direwolf79** [comment]
So far so good... Many thanks, and Happy/Merry whom/whatever you follow this holiday season ;)

**Comment by leoherran-aws** [comment]
Good to hear, feel free to reopen this with any related issues. Likewise!
