### ISSUE TITLE
Encoding of buildSpecFile

### ISSUE THREAD

**Issue by devnoo** [awslabs/aws-codebuild-jenkins-plugin#88]
When i pass in an inline buildspec, to the plugin it escapes all quotes and greater thens etc. 
This breaks the file, because it does not get decode on the code build side

so a statement like this will get quotes replaced by &quote etc.
- node -pe '"aws_access_key_id = " + JSON.parse(process.argv[1]).Credentials.AccessKeyId' "$temp_role" >> ~/.aws/credentials

and code build can't understand it anymore
I can't find a way to work around it except for passing a file reference, but in this case that won't work for me .

**Comment by leoherran-aws** [comment]
Fixed in e21bbac4e01fb77845746cbf2717ba8d147a557d. I relaxed the buildspec override validation so no special characters are encoded. This will be released in version `0.45` which should be available later today.
