### ISSUE TITLE
Logs not retrieve from cloud watch

### ISSUE THREAD

**Issue by TruffleMuffin** [awslabs/aws-codebuild-jenkins-plugin#9]
CodeBuilder.java never sets the logsLocation from the Build objective for the logsMonitor to use. This results in the dashboard never getting any log information.

Will issue a pull request for this shortly.

**Comment by TruffleMuffin** [comment]
On further investigation this is because the cloud watch client is not created with the correct region information.

**Comment by taoyong-ty** [comment]
The pull request had been merged to the master branch. Resolving this issue..
