### ISSUE TITLE
Missing blog post

### ISSUE THREAD

**Issue by strohm-a** [awslabs/aws-codebuild-jenkins-plugin#94]
The blog post referenced is no longer available: https://aws.amazon.com/blogs/devops/simplify-your-jenkins-builds-with-aws-codebuild/

Please correct the URL, or pull the relevant information into the readme file.

Thanks,

Strohm

**Comment by leoherran-aws** [comment]
Updated README in ff366e893e9d3e7ff2b065198f990da5749ca466.
